### ISSUE TITLE
import error when trying to execute flowgraph

### ISSUE THREAD

**Issue by alexxmarsh44** [ghostop14/gr-correctiq#13]
I am using GNURadio 3.8.1.0 and setup up your block with no problems but when I add any of the new blocks to a flowgraph and try to execute it I get this error on arch linux:

Traceback (most recent call last):
  File "/home/alexx/yagitest.py", line 35, in <module>
    import correctiq
  File "/usr/lib/python3.8/site-packages/correctiq/__init__.py", line 27, in <module>
    from .correctiq_swig import *
  File "/usr/lib/python3.8/site-packages/correctiq/correctiq_swig.py", line 13, in <module>
    from . import _correctiq_swig
ImportError: libgnuradio-correctiq.so.3.0.0git: cannot open shared object file: No such file or directory

>>> Done (return code 1)

Any idea how to fix this?  I really want to get this working thanks.

**Comment by ghostop14** [comment]
Sounds like the LD_LIBRARY path doesn't include wherever the library got installed.  I'd recommend searching for libgnuradio-correctiq.so on your file system and make sure it's in the library path.

**Comment by 34V35DR0PP3R** [comment]
Same problem here, I checked my LD_LIBRARY variable and it contains the path to "libgnuradio-correctiq.so".
Just fyi, I see the new blocks in GNURADIO and I can set them up etc etc. I just can't run it anymore

**Comment by ghostop14** [comment]
Definitely sounds like an install path.  If you do a find for that file, where did it get installed?
